### ISSUE TITLE
Toolbar is collapsed all the time, why ?

### ISSUE THREAD

**Issue by nku-bsw** [nhn/tui.editor#1761]
Hi i have a Problem with the Editors Toolbar and i can't figure it out how to solve it. 
The Toolbar is always collapsed. 
![image](https://user-images.githubusercontent.com/65232244/129905954-77a3f8c1-2dee-49c8-9af6-a1b8979fcb0f.png)
It should got enough width.  I don't know why it's happening. 
It's putting everything in a `class="toastui-editor-toolbar-group"` 
![image](https://user-images.githubusercontent.com/65232244/129906347-674dfcae-688a-4404-a815-e3e750194a5d.png)
I use Editor in multiple Tabs and when i load the first Tab everything is ok, but when i go through the other Tabs the Toolbar is always collapsed. When i then open the console everything goes back to normal behaviour. We also forked your repo and edited  it so that it's still compatible with React: v16.

## Summary
How can i solve my Problem ?

## Version
3.0.0

## Additional context
Here is my code maybe this helps:
`
import '@toast-ui/editor/dist/toastui-editor.css';
import { Editor, Viewer } from '@toast-ui/react-editor';

export interface MarkdownEditorProps {
  onChange: (value: string) => void;
  value: string;
}

export default function MarkdownEditor({onChange, value}: MarkdownEditorProps) {
  const editorRef: any = useRef(null);
  return (
    <div className="w-100">
      <Editor
        previewStyle="vertical"
        height="400px"
        initialEditType="wysiwyg"
        initialValue={value || ''}
        ref={editorRef}
        onChange={(EditorType: 'wysiwyg' | 'markdown') => {
          const markdownText = editorRef.current.getInstance().getMarkdown();
          onChange(markdownText);
        }}
        usageStatistics={false}
        toolbarItems={[
          ['heading', 'bold', 'italic', 'strike'],
          ['hr', 'quote'],
          ['ul', 'ol', 'task', 'indent', 'outdent'],
          ['table', 'image', 'link'],
          ['code', 'codeblock'],
          ['scrollSync']
        ]}
      />
    </div>
  );
}
`

**Comment by js87zz** [comment]
@nku-bsw 
The issue has been fixed in `v3.0.3`
Can you update to `v3.0.3`?

**Comment by nku-bsw** [comment]
@js87zz  We updated the Version but there is still the same issue :/

**Comment by js87zz** [comment]
@nku-bsw 
Can you give me your example on the code sandbox?

**Comment by nku-bsw** [comment]
@js87zz 
If found the issue. After i installed "@toast-ui/editor": "^3.0.3" & "prosemirror-transform": "^1.3.2" is everything working. Before we had only "@toast-ui/react-editor": "^3.0.3" installed

**Comment by nku-bsw** [comment]
@js87zz 
https://stackblitz.com/edit/blue-react-app-stackblitz-xuxprf?file=pages%2FHomePage.tsx
I couldn't reproduce the Problem. But maybe i did something wrong while installing. I only installed "@toast-ui/react-editor": "3.0.3". Do i need to install something else too ?

**Comment by js87zz** [comment]
@nku-bsw 
There's nothing else to install. The problem has been solved?🧐

**Comment by nku-bsw** [comment]
@js87zz
Yes it has been solved. Thanks for the help :)
