### ISSUE TITLE
How do I prevent the Toast UI Editor from getting focus when it is rendered

### ISSUE THREAD

**Issue by benderillo** [nhn/tui.editor#1802]
## Summary
I have a NextJS app that contains the toast-ui/react-editor.
The editor is not visible and I have a button that controls visibility by toggling the `show` state variable this way:
```javascript
export function MyEditor({placeholder}) {
const [show, setShow] = useState(false);
const editorRef = useRef(null);

  return (
    <div class="root">
      <div class="editor-container">
        {show && <Editor
              ref={editorRef}
              placeholder={placeholder}
              previewStyle='tab'
              theme='dark'
              minHeight='300px'
              height='300px'
              initialEditType='markdown'
              hooks={{
                addImageBlobHook: onAddImageBlob,
              }}
              autofocus={false}
        />}
      </div>
    </div>
  );
}
```

Please note that I am passing the `autofocus` property `false` but the editor's text area gets activated as soon as the editor is rendered.

How do I turn it off?

## Version
    "@toast-ui/editor": "^3.1.0",
    "@toast-ui/react-editor": "^3.1.0",

**Comment by js87zz** [comment]
@benderillo 
Can you give me your example in code sandbox?
When I tested in a react environment, there was no focus problem.

**Comment by benderillo** [comment]
@js87zz https://codesandbox.io/s/react-typescript-forked-4exdi?file=/src/editor.tsx

When the editor is shown, the focus is in the text area.

**Comment by js87zz** [comment]
@benderillo 
I checked the issue. Thanks for reporting!

**Comment by suregi** [comment]
I have the same issue. This happens when previewStyle is the "tab". Seems ok with "vertical" or when initialEditType is "wysiwyg". Here's the simplest dupe code:

```
<Editor
	previewStyle="tab"
	initialEditType="markdown"
	initialValue={'abc'}
	events={{
		focus: () => {
			console.log('⭐ focus');
		},
	}}
	autofocus={false}
/>
```

**Comment by volkflo** [comment]
Did somebody found a solution for that? :)

**Comment by volkflo** [comment]
I am not very familiar with your codebase, but from a quick view and debug session I would assume/guess that:
https://github.com/nhn/tui.editor/blob/253a9a086f5a8ff76a1f7a4be5e104c0b0e44b8c/apps/editor/src/base.ts#L172-L178
The `scrollIntoView` should be probably inside the `if` - block.
I guess the expected behaviour of `autoFocus: false` would be that the page does not scroll as well (See video in #1945).

I hope that helps a little bit.

**Comment by js87zz** [comment]
@benderillo 
The bug has been fixed in `v3.1.2`. Thanks for long waiting!

**Comment by livevsonline** [comment]
This is very much not fixed... it auto focuses for me in 3.1.7 i have implemented several different places with several different options... and it does autofocus, is there a way to disable this?

Also, it would be epic to be able to set tab index -1

**Comment by livevsonline** [comment]
> 

Oh, its now has an option called autofocus in the `oSettings` object

**Comment by skerit** [comment]
Even though the autofocus doesn't happen anymore, the `scrollIntoView` still gets executed.
https://github.com/nhn/tui.editor/blob/0c5c11bac0b9954e2cac2ff2a081ce8c80a5f14d/apps/editor/src/base.ts#L199

**Comment by cragravorem** [comment]
Hello, I am also suffering from this automatic scroll problem with disabled autofocus. Is there any chance this issue could be reopened? Or, maybe, it is better to report it in another issue here?

**Comment by csculley** [comment]
I'm also seeing this behavior in Toast version 3.2.2 with `autofocus: false`

**Comment by xen** [comment]
I have the same problem. Setting `autofocus: false` doesn't affect editor. It still grabs the focus.

**Comment by zeturn** [comment]
same question

You see, here is my development service : https://pilipala.ml/wall/C++. 
Once you enter this page, the editor will catch the focus. And here is my app.js:
```javascript
import '@toast-ui/editor/dist/toastui-editor.css';

const editor = new Editor({
  el: document.querySelector('#editor'),
  height: '400px',
  initialEditType: 'markdown',
  placeholder: '6!',
  language: 'zh-CN',
  autofocus: false,
})
```

​Did I make some mistakes in this instance?
Thank you : )

**Comment by tfolk** [comment]
Same here

**Comment by csculley** [comment]
@js87zz I'm not sure that this bug was fixed completely, could this issue be reopened? Right now there are 6 reports of this issue still existing

**Comment by zeturn** [comment]
I placed ```autofocus: false``` in the middle and re executed ```npm run dev``` and it works, which is strange


this is my app.js
```javascript
//tui editor
import Editor from '@toast-ui/editor'
//import 'codemirror/lib/codemirror.css';
import '@toast-ui/editor/dist/toastui-editor.css';

const editor = new Editor({
  el: document.querySelector('#editor'),
  height: '300px',
  initialEditType: 'markdown',
  autofocus : false,
  placeholder: '发表见解',
  language: 'zh-CN',
})
```

In addition, the United States has removed the. ml domain name, which means that the website I mentioned (pilipala.ml) cannot be used. That domain name has been with me for 5 years

**Comment by tfolk** [comment]
autofocus: false works for me!

**Comment by seungwoncode** [comment]
"@toast-ui/react-editor": "^3.2.3" 

autoFocus is not working for me .

I solved the problem by correcting it in the following way.

```js
 useEffect(() => {
    if (editorRef.current) {
      const timeoutBlur = setTimeout(() => {
        editorRef.current?.getInstance().blur();
      }, 0);

      return () => {
        clearTimeout(timeoutBlur);
      };
    }
  }, [editorRef, content]);
```

Among the other methods I've applied, I've given focus elsewhere and removed it, but maybe because the TUI editor is slow to load, when the editor is rendered at the end, it's unconditionally focused on editor. So I chose to deal with it inside useEffect.

**Comment by mladen-orsolic** [comment]
This issue still persists in latest version. Its easily reproducible when you have multiple instances (that contain some text) in a vertically scrollable div. It will auto scroll to the end of text in last editor, and it will cause to containing div to scroll to the last editor. Autofocus has no effect here and i'm unable to prevent this behaviour using css and/or javascript.

css:
```
  overflowAnchor: 'none', // on the container
  '& *': {
    overflowAnchor: 'none', // apply to all child editors and its children too
  },
```

react:
```
  // Force blur after mount or value change if autoFocus is false
  useEffect(() => {
    if (!autoFocus && editable && editorRef.current) {
      const editorInstance = editorRef.current.getInstance();
      const { mdEditor, wwEditor } = editorInstance.getEditorElements();

      // Blur both markdown and WYSIWYG editors
      if (mdEditor instanceof HTMLElement) {
        mdEditor.blur();
        mdEditor.scrollTop = 0;
      }
      if (wwEditor instanceof HTMLElement) {
        wwEditor.blur();
        wwEditor.scrollTop = 0;
      }
    }
  }, [editorRef, autoFocus]);
```

none of this helps preventing the focus and autoscroll

it works fine when initialEditType is "markdown", which i dont want, i want initialEditType to be "wysiwyg" 

seems the problem is on the diw with class : class="ProseMirror toastui-editor-contents"
which has contenteditable="true" and that automatically sets the focus and ignores autoFocus completely cuasing unwanted scrolls too.
